// Code generated by sqlc. DO NOT EDIT.

package pg

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Contents  string
	UserID    int32
	PostID    int32
}

type Follower struct {
	ID         int32
	CreatedAt  time.Time
	LeaderID   int32
	FollowerID int32
}

type Hashtag struct {
	ID        int32
	CreatedAt time.Time
	Title     string
}

type Like struct {
	ID        int32
	CreatedAt time.Time
	UserID    int32
	PostID    int32
	CommentID int32
}

type Post struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Url       string
	Caption   string
	Lat       sql.NullFloat64
	Lng       sql.NullFloat64
	UserID    int32
}

type User struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Bio       string
	Avatar    string
	Email     string
	Password  string
}
